---

- hosts: all
  become: true
  pre_tasks:                          # pre_tasks   - this section will run first before any other tasks

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only:  yes
      update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade:  dist
      update_cache: yes
    when: ansible_distribution == "Ubunto"  

- hosts:  web_servers
  become: true
  tasks:

  - name: install apache add php for ubuntu servers
    tags: apache,apache2,ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state:  latest
    when: ansible_distribution == "Ununtu"

  - name: install apache add php for centOS servers
    tags: apache,centos,httpd
    dnf: 
      name:
        - httpd
        - php
      state:  latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:                                    # copy module     
      src:  default_site.html
      dest: /var/www/html/index.html         # destination file name (can be different name from the source)          
      owner:  root
      group:  root
      mode: 0644              # set file permissions

- hosts:  db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf: 
      name: mariadb
      state:  latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt: 
      name: mariadb-server
      state:  latest
    when: ansible_distribution == "Ubuntu"
    
- hosts:  file_servers
  become: true
  tasks:

  - name: install samba package 
    tags: samba
    package: 
      name: samba
      state:  latest        
