---

- hosts: all
  become: true
  pre_tasks:                          # pre_tasks   - this section will run first before any other tasks

  - name: install updates (CentOS)
    dnf:
      update_only:  yes
      update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: install updates (Ubuntu)
    apt:
      upgrade:  dist
      update_cache: yes
    when: ansible_distribution == "Ubunto"  

- hosts:  web_servers
  become: true
  tasks:

  - name: install apache add php for ubuntu servers
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state:  latest
    when: ansible_distribution == "Ununtu"

  - name: install apache add php for centOS servers
    dnf: 
      name:
        - httpd
        - php
      state:  latest
    when: ansible_distribution == "CentOS"

- hosts:  db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf: 
      name: mariadb
      state:  latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb-server
      state:  latest
    when: ansible_distribution == "Ubuntu"
    
- hosts:  file_servers
  become: true
  tasks:

  - name: install samba package 
    package: 
      name: samba
      state:  latest        
