- name: install unzip                 # using unzip , install it
  package:
    name: unzip

- name: install terraform             # install terraform - for cloud management
  unarchive:
    src:  https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
    mode: 0755
    owner:  root
    group:  root